language: python

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - TOXENV=django111
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

matrix:
  include:
    - python: 2.7
      env: TOXENV=quality
  allow_failures:
    - python: 3.6
    - python: 3.7
    - python: 2.7
      env: TOXENV=django20
    - python: 2.7
      env: TOXENV=django21
    - python: 2.7
      env: TOXENV=django22


cache:
  - pip

install:
    - pip install -U codecov pip wheel
    - make requirements

script:
  - tox

after_success:
  - codecov

deploy:
    provider: pypi
    user: edx
    password:
         secure: dQKjSK9Tf7VM8SzoYxZy5zsdhOojRG1FNO0IbTvdiDQ2HwtPRwHycAoustFiUqgXxUT4cHdvm1kLlRaf+W4LHMaBqzw3MPuYMETrvS/WghbVx3yzGgMtjffFhd/QgnqX+nP3Q6JE0/NXm7iVGj8TSK0Wu7Vae5OcJe1I4qgHbdU=
    distributions: sdist bdist_wheel
    on:
        tags: true
