sudo: false
language: python
python:
  - "2.7"
# command to install dependencies
install:
    - "pip install coveralls"
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
# command to run tests
script: coverage run ./manage.py test --settings=tests.settings

after_success: coveralls

deploy:
    provider: pypi
    user: edx
    password:
         secure: dQKjSK9Tf7VM8SzoYxZy5zsdhOojRG1FNO0IbTvdiDQ2HwtPRwHycAoustFiUqgXxUT4cHdvm1kLlRaf+W4LHMaBqzw3MPuYMETrvS/WghbVx3yzGgMtjffFhd/QgnqX+nP3Q6JE0/NXm7iVGj8TSK0Wu7Vae5OcJe1I4qgHbdU=
    distributions: sdist bdist_wheel
    on:
        tags: true
